apiVersion: v1
kind: Service             
metadata:
  name: frontend-np
spec:
  type: NodePort
  ports:
  - port: {{ .Values.frontend.port }}
    protocol: TCP          
    nodePort: {{ .Values.frontend.nodePort }}
  selector:                
    app: frontend       

