apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: web-app
spec:
  selector:
    matchLabels:
      app: web-app
  replicas: {{ .Values.replicaCount }}
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - image: sergysa/sentiment-analysis-web-app
        imagePullPolicy: Always
        name: web-app
        env:
          - name: SA_LOGIC_API_URL
            value: "http://logic:{{ .Values.logic.port }}"
        ports:
          - containerPort: {{ .Values.webapp.containerPort }}

